### ISSUE TITLE
Get rid of unnecessary dependencies

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensingClient-javascript#2]
Version 1.0.0 defines `xmlhttprequest` as dependency: https://github.com/Labs64/NetLicensingClient-javascript/blob/master/package.json#L65

We should naintain as less as possible dependencies in the project, so please verify possibility to delete this dependency.

**Comment by v-rudkovskiy** [comment]
Done in [Labs64/NetLicensingClient-javascript@23636c3](https://github.com/Labs64/NetLicensingClient-javascript/commit/23636c3e3eb2a78a308d92d7ca6c6b46ea8c415b)

**Comment by v-rudkovskiy** [comment]
@r-brown Please review
