### ISSUE TITLE
eslint-utils vulnerability

### ISSUE THREAD

**Issue by kkorotkov** [Labs64/NetLicensingClient-javascript#7]
https://github.com/Labs64/NetLicensingClient-javascript/network/alert/package-lock.json/eslint-utils/open
https://github.com/mysticatea/eslint-utils/security/advisories/GHSA-3gx7-xhv7-5mx3

**Comment by r-brown** [comment]
TravisCI build is broken - https://travis-ci.org/Labs64/NetLicensingClient-javascript/builds/578268010

**Comment by r-brown** [comment]
Node versions 6 and 7 deleted - please always align such changes.
As of now support for node.js 6/7 still expected.
